image: Visual Studio 2019
configuration: Debug
platform: x64
before_build:
- cmd: scripts\generate-version.bat
build:
  project: AirDC.sln
  parallel: true
  verbosity: normal

init:
  # Set "build version number" to "short-commit-hash" or when tagged to "tag name" (Travis style)
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }
      else
      {
        Update-AppveyorBuild -Version "dev-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
      }
